### ISSUE TITLE
Dataset generation script

### ISSUE THREAD

**Issue by imoneoi** [meta-math/MetaMath#1]
Could you please publish the dataset generation script? This will ensure reproducibility and make a good contribution to the open-source LLM community.

**Comment by yulonghui** [comment]
Hi~ imoneoi, Thanks for your attention! We will definitely publish the dataset generation script, I think it will be around early October. Also, A 40K subset of our Full MetaMathQA dataset is released in the huggingface [MetaMathQA](https://huggingface.co/datasets/meta-math/MetaMathQA/tree/main). 
The full MetaMathQA dataset will be opened very soon because we are still using this data for fully fine-tuning the 70B model.

**Comment by imoneoi** [comment]
Thank you! Looking forward to your releases!

**Comment by imoneoi** [comment]
Hi @yulonghui, any updates?

**Comment by yulonghui** [comment]
> Hi @yulonghui any updates on the script? We'd like to regenerate it with Mixtral with the aim of not being restricted by OpenAI terms on the current GPT generated dataset.
Hi, @dctanner 
we have open-sourced our data generation scripts on https://github.com/meta-math/MetaMath/tree/main/code_for_generating_data already.
Sorry for the late reminder. 
It is very interesting to regenerate it with Mixtral. I'm looking forward to seeing your results.
